name: Deploy Next.js App

on:
  push:
    branches:
      - main  # Déclenche le déploiement sur chaque push sur `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Ajouter la clé SSH privée et configurer SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.61.23.56 >> ~/.ssh/known_hosts  # Remplace par ton IP

      - name: Vérifier la connexion SSH
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@13.61.23.56 "echo 'Connexion SSH réussie'"

      - name: Corriger les permissions du dépôt
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@13.61.23.56 << 'EOF'
          sudo chown -R ubuntu:ubuntu /home/ubuntu/my-cicd-app
          sudo chmod -R 755 /home/ubuntu/my-cicd-app
          EOF

      - name: Déployer sur le serveur
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=10 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@13.61.23.56 << 'EOF'
          cd /home/ubuntu/my-cicd-app || git clone https://github.com/Dev02JL/my-cicd-app.git /home/ubuntu/my-cicd-app && cd /home/ubuntu/my-cicd-app
          git fetch origin main
          git reset --hard origin/main
          npm install
          npm run build
          sudo chown -R ubuntu:ubuntu /home/ubuntu/my-cicd-app/.next
          sudo chmod -R 755 /home/ubuntu/my-cicd-app/.next
          pm2 restart next-app --update-env
          pm2 save
          EOF